import pandas as pd

def fix_studies(dataframe: pd.DataFrame) -> pd.DataFrame:

    df_ = dataframe.copy()

    df_.loc[df_['fields_of_study'] == 'Bilgisayar Mühendisliği', 'fields_of_study'] = 'Computer Engineering'
    df_.loc[df_['fields_of_study'] == 'Elektrik ve Elektronik Mühendisliği', 'fields_of_study'] = 'Electrical and Electronics Engineering'
    df_.loc[df_['fields_of_study'] == 'Bilgisayar Programlama', 'fields_of_study'] = 'Computer Programming'
    df_.loc[df_['fields_of_study'] == 'bilgisayar programcılığı', 'fields_of_study'] = 'Computer Programming'
    df_.loc[df_['fields_of_study'] == 'Bilgisayar Programcılığı', 'fields_of_study'] = 'Computer Programming'
    df_.loc[df_['fields_of_study'] == 'bilgilsayar programcılığı', 'fields_of_study'] = 'Computer Programming'
    df_.loc[df_['fields_of_study'] == 'Matematik', 'fields_of_study'] = 'Mathematics'
    df_.loc[df_['fields_of_study'] == 'İşletme ve Yönetim, Genel', 'fields_of_study'] = 'Business Administration and Management, General'
    df_.loc[df_['fields_of_study'] == 'Bilgisayar Yazılımı Mühendisliği', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Yazılım Mühendisliği', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Endüstri Mühendisliği', 'fields_of_study'] = 'Industrial Engineering'
    df_.loc[df_['fields_of_study'] == 'Makine Mühendisliği', 'fields_of_study'] = 'Mechanical Engineering'
    df_.loc[df_['fields_of_study'] == 'Fizik', 'fields_of_study'] = 'Physics'
    df_.loc[df_['fields_of_study'] == 'Ekonomi', 'fields_of_study'] = 'Economics'
    df_.loc[df_['fields_of_study'] == 'İstatistik', 'fields_of_study'] = 'Statistics'
    df_.loc[df_['fields_of_study'] == 'Kimya', 'fields_of_study'] = 'Chemistry'
    df_.loc[df_['fields_of_study'] == 'Elektrik Mühendisliği', 'fields_of_study'] = 'Electrical Engineering'
    df_.loc[df_['fields_of_study'] == 'Elektrik mühendisliği', 'fields_of_study'] = 'Electrical Engineering'
    df_.loc[df_['fields_of_study'] == 'Elektrik Mühendisliği', 'fields_of_study'] = 'Electrical Engineering'
    df_.loc[df_['fields_of_study'] == 'Elektrik Mühendisi', 'fields_of_study'] = 'Electrical Engineering'
    df_.loc[df_['fields_of_study'] == 'elektrik mühendisliği', 'fields_of_study'] = 'Electrical Engineering'
    df_.loc[df_['fields_of_study'] == 'bilgisayar mühendisliği', 'fields_of_study'] = 'Computer Engineering'
    df_.loc[df_['fields_of_study'] == 'bilgisayar mühendisliği ', 'fields_of_study'] = 'Computer Engineering'
    df_.loc[df_['fields_of_study'] == 'bilgisayar mühendisligi', 'fields_of_study'] = 'Computer Engineering'
    df_.loc[df_['fields_of_study'] == 'bilgisayar müh.', 'fields_of_study'] = 'Computer Engineering'
    df_.loc[df_['fields_of_study'] == 'bilgisayar mühendisi', 'fields_of_study'] = 'Computer Engineering'
    df_.loc[df_['fields_of_study'] == 'yönetim bilişim sistemleri', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Yönetim Bilişim Sistemleri', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Computer Engineering BSC', 'fields_of_study'] = 'Computer Engineering' 
    df_.loc[df_['fields_of_study'] == 'Computer Engineering, BE', 'fields_of_study'] = 'Computer Engineering' 
    df_.loc[df_['fields_of_study'] == ' Computer Engineering', 'fields_of_study'] = 'Computer Engineering'
    df_.loc[df_['fields_of_study'] == 'computer engineering', 'fields_of_study'] = 'Computer Engineering'
    df_.loc[df_['fields_of_study'] == 'computer engineer', 'fields_of_study'] = 'Computer Engineering'
    df_.loc[df_['fields_of_study'] == 'computer engineerig', 'fields_of_study'] = 'Computer Engineering'
    df_.loc[df_['fields_of_study'] == 'computer engeneering', 'fields_of_study'] = 'Computer Engineering'
    df_.loc[df_['fields_of_study'] == 'computer science', 'fields_of_study'] = 'Computer Science'
    df_.loc[df_['fields_of_study'] == 'Bilgisayar Bilimleri', 'fields_of_study'] = 'Computer Science'
    df_.loc[df_['fields_of_study'] == 'computer sciences', 'fields_of_study'] = 'Computer Science'
    df_.loc[df_['fields_of_study'] == 'computer scientist', 'fields_of_study'] = 'Computer Science'
    df_.loc[df_['fields_of_study'] == 'computer Engineering', 'fields_of_study'] = 'Computer Engineering' 
    df_.loc[df_['fields_of_study'] == 'computer Engineer', 'fields_of_study'] = 'Computer Engineering' 
    df_.loc[df_['fields_of_study'] == 'computer programming', 'fields_of_study'] = 'Computer Programming'
    df_.loc[df_['fields_of_study'] == 'computer programmer', 'fields_of_study'] = 'Computer Programming'
    df_.loc[df_['fields_of_study'] == 'Bilgisayar Programlama/Programcı, Genel', 'fields_of_study'] = 'Computer Programming'
    df_.loc[df_['fields_of_study'] == 'elektrik elektronik mühendisliği', 'fields_of_study'] = 'Electrical and Electronics Engineering'
    df_.loc[df_['fields_of_study'] == 'elektrik elektronik mühendisi', 'fields_of_study'] = 'Electrical and Electronics Engineering'
    df_.loc[df_['fields_of_study'] == 'elektrik elektronik', 'fields_of_study'] = 'Electrical and Electronics Engineering'
    df_.loc[df_['fields_of_study'] == 'endüstri mühendisliği', 'fields_of_study'] = 'Industrial Engineering'
    df_.loc[df_['fields_of_study'] == 'Endüstri Mühendisliği/Industrial Engineering', 'fields_of_study'] = 'Industrial Engineering'
    df_.loc[df_['fields_of_study'] == 'Endüstri Mühendisliği / Industrial Engineering', 'fields_of_study'] = 'Industrial Engineering'
    df_.loc[df_['fields_of_study'] == 'Endüstri Mühendisliği, Mühendislik Yönetimi ', 'fields_of_study'] = 'Industrial Engineering'
    df_.loc[df_['fields_of_study'] == 'Endüstri Mühendisi', 'fields_of_study'] = 'Industrial Engineering'
    df_.loc[df_['fields_of_study'] == 'Endüstri Mühendisliği Yüksek Lisans', 'fields_of_study'] = 'Industrial Engineering'
    df_.loc[df_['fields_of_study'] == 'Endüstri Mühendisliği-Mühendislik Yönetimi', 'fields_of_study'] = 'Industrial Engineering'
    df_.loc[df_['fields_of_study'] == 'Endüstri Mühendisliği (Tezli)', 'fields_of_study'] = 'Industrial Engineering'
    df_.loc[df_['fields_of_study'] == 'Endüstri Mühendisliği / Müh. Yönetimi ', 'fields_of_study'] = 'Industrial Engineering'
    df_.loc[df_['fields_of_study'] == 'Endüstri Mühendisliği Ana Bilim Dalı', 'fields_of_study'] = 'Industrial Engineering'
    df_.loc[df_['fields_of_study'] == 'Endüstri Mühendisliği Lisans', 'fields_of_study'] = 'Industrial Engineering'
    df_.loc[df_['fields_of_study'] == 'Endüstri Mühendisliği Yöneylem Araştırması Anabilim Dalı', 'fields_of_study'] = 'Industrial Engineering'
    df_.loc[df_['fields_of_study'] == 'Endüstri Mühendisliği (EN)', 'fields_of_study'] = 'Industrial Engineering'
    df_.loc[df_['fields_of_study'] == 'Endüstri Mühendisliği - Yan Dal Programı', 'fields_of_study'] = 'Industrial Engineering'
    df_.loc[df_['fields_of_study'] == 'Lisans-Endüstri Mühendisliği', 'fields_of_study'] = 'Industrial Engineering'
    df_.loc[df_['fields_of_study'] == 'Endüstri Mühendisliği, Tam Burslu', 'fields_of_study'] = 'Industrial Engineering'
    df_.loc[df_['fields_of_study'] == 'Endüstri Mühendisliği (Minor)', 'fields_of_study'] = 'Industrial Engineering'
    df_.loc[df_['fields_of_study'] == 'Industrial Engineering (Endüstri Mühendisliği)', 'fields_of_study'] = 'Industrial Engineering'
    df_.loc[df_['fields_of_study'] == 'Sistem Mühendisliği (Endüstri Mühendisliği)', 'fields_of_study'] = 'Industrial Engineering'
    df_.loc[df_['fields_of_study'] == 'Industrial Engineering / Endüstri Mühendisliği', 'fields_of_study'] = 'Industrial Engineering'
    df_.loc[df_['fields_of_study'] == 'Endüstri Mühendisliği (Industrial Engineer)', 'fields_of_study'] = 'Industrial Engineering'
    df_.loc[df_['fields_of_study'] == 'Endüstri Mühendisliği lisans', 'fields_of_study'] = 'Industrial Engineering'
    df_.loc[df_['fields_of_study'] == 'matematik', 'fields_of_study'] = 'Mathematics' 
    df_.loc[df_['fields_of_study'] == 'matematik(ingilizce)', 'fields_of_study'] = 'Mathematics'
    df_.loc[df_['fields_of_study'] == 'kimya', 'fields_of_study'] = 'Chemistry'
    df_.loc[df_['fields_of_study'] == 'KİMYA', 'fields_of_study'] = 'Chemistry'
    df_.loc[df_['fields_of_study'] == 'KİMYAGER', 'fields_of_study'] = 'Chemistry'
    df_.loc[df_['fields_of_study'] == 'Business Administration and Management, General', 'fields_of_study'] = 'Business Administration and Management'
    df_.loc[df_['fields_of_study'] == 'Business Administration and Management', 'fields_of_study'] = 'Business Administration and Management'
    df_.loc[df_['fields_of_study'] == 'Business Administration and Management (English)', 'fields_of_study'] = 'Business Administration and Management'
    df_.loc[df_['fields_of_study'] == 'Business Administration and Management, Technology Track', 'fields_of_study'] = 'Business Administration and Management'
    df_.loc[df_['fields_of_study'] == 'Business Administration and Management, MBA', 'fields_of_study'] = 'MBA'
    df_.loc[df_['fields_of_study'] == 'Business Administration and Management, Executive', 'fields_of_study'] = 'Business Administration and Management'
    df_.loc[df_['fields_of_study'] == 'Business Administration and Management (Master)', 'fields_of_study'] = 'Business Administration and Management'
    df_.loc[df_['fields_of_study'] == 'Business Administration and Management (German)', 'fields_of_study'] = 'Business Administration and Management'
    df_.loc[df_['fields_of_study'] == 'Business Administration and Management.Open University', 'fields_of_study'] = 'Business Administration and Management'
    df_.loc[df_['fields_of_study'] == 'Faculty of Business Administration and Management', 'fields_of_study'] = 'Business Administration and Management'
    df_.loc[df_['fields_of_study'] == 'Bachelor of Business Administration, Business Administration and Management', 'fields_of_study'] = 'Business Administration and Management'
    df_.loc[df_['fields_of_study'] == 'Istanbul Master degree in Business Administration and Management, General', 'fields_of_study'] = 'Business Administration and Management'
    df_.loc[df_['fields_of_study'] == 'Business Administration and Management, Toronto ON ', 'fields_of_study'] = 'Business Administration and Management'
    df_.loc[df_['fields_of_study'] == 'Business Administration and Management, Marketing', 'fields_of_study'] = 'Business Administration and Management'
    df_.loc[df_['fields_of_study'] == 'MAKİNE MÜHENDİSLİĞİ', 'fields_of_study'] = 'Mechanical Engineering'
    df_.loc[df_['fields_of_study'] == 'BİLGİSAYAR PROGRAMCILIĞI', 'fields_of_study'] = 'Computer Programming'
    df_.loc[df_['fields_of_study'] == 'BİLGİSAYAR MÜHENDİSLİĞİ', 'fields_of_study'] = 'Computer Engineering'
    df_.loc[df_['fields_of_study'] == 'BİLGİSAYAR PROGRAMCILIĞI - ÖN LİSANS', 'fields_of_study'] = 'Computer Programming'
    df_.loc[df_['fields_of_study'] == 'yazılım mühendisliği', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'yazılım mühendisliği ', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'yazılım mühendiliği', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'yazılım mühendisligi', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'yazılım mühendisi', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Yazılım mühendisliği', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Yazılım mühendisliği ', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Yazılım mühendisi', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Yazılım Mühendisi', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Yazılım Mühendisliği ', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Yazılım Mühendislik', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == ' Yazılım Mühendisliği', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Yazılım Mühendisliği / Software Engineering', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Yazılım Mühendisliği (Çift Anadal)', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Yazılım Mühendisliği Yüksek Lisans Programı', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Yazılım Mühendisliği ve Veri Bilimi', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Yazılım Mühendisliği(İngilizce)', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Yazılım Mühendisliği Software Engineering', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Yazılım Mühendisliği MS', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Yazılım Mühendisliği (UOLP)', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Yazılım Mühendisliği (%100 Burslu)', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Yazılım Mühendisliği(Software Engineering)', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Bilgisayar Bilimleri Fakültesi, Yazılım Mühendisliği', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Software Engineering - Yazılım Mühendisliği', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Yazılım Müh.', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Yazılım Mühendisliği (Uzaktan)', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Yazılım Mühendisliği , Ortalama :  3.1 / 4', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Yazılım Mühendisliği ( Ingilizce )', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Yazılım Mühendisliği U.O.L.P (ingilizce)', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Yazılım Mühendisliği (EN/TR)', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Yazılım Mühendisliği(EN/TR), Comprehensive Scholarship (%100)', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Yazılım Mühendisliği(English)', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Bilgisayar Yazılım Mühendisliği', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Yazılım Mühendisligi', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Yazılım Mühendisliği; Bilgisayar Tek. ve Prog', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Bilgisayar ve Yazılım Mühendisliği', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Yazılım Mühendisliğ', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Yazılım Mühendisliği (Software Engineering)', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Sofware Developer', 'fields_of_study'] = 'Software Developer'
    df_.loc[df_['fields_of_study'] == 'Sofware Engineer', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Sofware Engineering', 'fields_of_study'] = 'Software Engineering'
    df_.loc[df_['fields_of_study'] == 'Computer science', 'fields_of_study'] = 'Computer Science'
    df_.loc[df_['fields_of_study'] == 'computer science', 'fields_of_study'] = 'Computer Science'
    df_.loc[df_['fields_of_study'] == 'Computer engineering', 'fields_of_study'] = 'Computer Engineering'
    df_.loc[df_['fields_of_study'] == 'Computer engineer', 'fields_of_study'] = 'Computer Engineering'
    df_.loc[df_['fields_of_study'] == 'Computer engineering ', 'fields_of_study'] = 'Computer Engineering'
    df_.loc[df_['fields_of_study'] == 'Computer engineerig', 'fields_of_study'] = 'Computer Engineering'
    df_.loc[df_['fields_of_study'] == 'Computer engineering and natural sciences faculty', 'fields_of_study'] = 'Computer Engineering'
    df_.loc[df_['fields_of_study'] == 'COMPUTER ENGINEERING', 'fields_of_study'] = 'Computer Engineering'
    df_.loc[df_['fields_of_study'] == '( ENG. FAC.) / COMPUTER ENGINEERING', 'fields_of_study'] = 'Computer Engineering'
    df_.loc[df_['fields_of_study'] == 'COMPUTER ENGINEER', 'fields_of_study'] = 'Computer Engineering'
    df_.loc[df_['fields_of_study'] == 'COMPUTER ENGİNEER', 'fields_of_study'] = 'Computer Engineering'
    df_.loc[df_['fields_of_study'] == 'COMPUTER ENGİNEERİNG', 'fields_of_study'] = 'Computer Engineering'
    df_.loc[df_['fields_of_study'] == 'business administration', 'fields_of_study'] = 'Business Administration'
    df_.loc[df_['fields_of_study'] == 'School of business administration', 'fields_of_study'] = 'Business Administration'
    df_.loc[df_['fields_of_study'] == 'school of business administration', 'fields_of_study'] = 'Business Administration'
    df_.loc[df_['fields_of_study'] == 'MBA(Master of business administration)', 'fields_of_study'] = 'Business Administration'
    df_.loc[df_['fields_of_study'] == 'business administrative  (english)', 'fields_of_study'] = 'Business Administration'
    df_.loc[df_['fields_of_study'] == 'Master of business administration (MBA)', 'fields_of_study'] = 'Business Administration'
    df_.loc[df_['fields_of_study'] == 'Master of business administration', 'fields_of_study'] = 'Business Administration'
    df_.loc[df_['fields_of_study'] == 'Statistic', 'fields_of_study'] = 'Statistics'
    df_.loc[df_['fields_of_study'] == 'Statictics', 'fields_of_study'] = 'Statistics'
    df_.loc[df_['fields_of_study'] == 'BSc, Statistics', 'fields_of_study'] = 'Statistics'
    df_.loc[df_['fields_of_study'] == 'B.Sc., Statistics', 'fields_of_study'] = 'Statistics'
    df_.loc[df_['fields_of_study'] == 'Statistic ', 'fields_of_study'] = 'Statistics'
    df_.loc[df_['fields_of_study'] == 'Statictics', 'fields_of_study'] = 'Statistics'
    df_.loc[df_['fields_of_study'] == 'Statistics (English)', 'fields_of_study'] = 'Statistics'
    df_.loc[df_['fields_of_study'] == 'Department of Statistics', 'fields_of_study'] = 'Statistics'
    df_.loc[df_['fields_of_study'] == 'Electronics and Communications Engineering', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'elektronik ve haberleşme mühendisliği', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'elektronik ve haberleşme ', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'elektronik ve haberlesme muhendisligi', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'elektronik ve haberleșme mühendisliği', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'elektronik ve haberleşme mühendisi', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'elektronik ve haberleşme mühendisi ', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'elektronik ve haberleşme mühendisligi', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'ELEKTRONİK VE HABERLEŞME MÜHENDİSLİĞİ', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'ELEKTRONİK VE HABERLEŞME', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'ELEKTRONİK HABERLEŞME', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'ELEKTRONİK HABERLEŞME MÜHENDİSLİĞİ', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'ELEKTRONİK HABERLEŞME TEKNOLOJİSİ', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'Master of Business Administration', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Master of Business Administration (MBA)', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Master of Business Administration - MBA', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Master of Business Adminstration', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Master of Business Administration (M.B.A.)', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Master of Business Administration(MBA)', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Executive Master of Business Administration', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'MBA (Master of Business Administration)', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Institute of Social Sciences, Master of Business Administration', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Master of Business Administrator (with Thesis)', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Master of Business Administrator', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Executive Master of Business Adminstrations', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Master of Business Administration MBA', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Master of Business Administration (MBA) (Without Thesis)', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Master of Business Administration (MBA) , Executive MBA', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Master of Business Administration (e-MBA)', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Master of Business Information Systems', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Master of Business Administration (MBA) - English', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'MBA, Master of Business Administration', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Master of Business Administration (MBA), Master degree', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Master of Business and Administration', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Master of Business Administration MBA - thesis program', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Master of Business Administration - MBA, Social Sciences', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Master of Business Administration (MBA), Hospital and Health Institutions Management', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Master’s degree • Master of Business Administration', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Master of Business Administration (M.B.A.), Executive M.B.A', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Master of Business Administration ', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Master of Business Administration,MBA', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'MBA - Master of Business Administration', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Master of Business Administration (M.B.A), Marketing/Marketing Management, General', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Master of Business Administration ( MBA )', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Master of Business Administration, MBA', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Management and Strategy - Master of Business Administration', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Master of Business Administration, Executive MBA', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Master of Business Administration in Finance', 'fields_of_study'] = 'Master of Business Administration'
    df_.loc[df_['fields_of_study'] == 'Matematik Mühendisliği', 'fields_of_study'] = 'Mathematical Engineering'
    df_.loc[df_['fields_of_study'] == 'Matematik Mühendisliği ', 'fields_of_study'] = 'Mathematical Engineering'
    df_.loc[df_['fields_of_study'] == 'Matematik Mühendisi', 'fields_of_study'] = 'Mathematical Engineering'
    df_.loc[df_['fields_of_study'] == 'Matematik Mühendisligi', 'fields_of_study'] = 'Mathematical Engineering'
    df_.loc[df_['fields_of_study'] == 'Matematik Mühendisliği (İngilizce)', 'fields_of_study'] = 'Mathematical Engineering'
    df_.loc[df_['fields_of_study'] == 'Matematik Mühendisliği(İngilizce)', 'fields_of_study'] = 'Mathematical Engineering'
    df_.loc[df_['fields_of_study'] == 'Matematik Mühendisliği, 3.39', 'fields_of_study'] = 'Mathematical Engineering'
    df_.loc[df_['fields_of_study'] == 'Matematik Mühendisliği (İng)', 'fields_of_study'] = 'Mathematical Engineering'
    df_.loc[df_['fields_of_study'] == 'Matematik Mühendisliği/ Mathematical Engineering', 'fields_of_study'] = 'Mathematical Engineering'
    df_.loc[df_['fields_of_study'] == 'Matematik Mühendisliği 3,22', 'fields_of_study'] = 'Mathematical Engineering'
    df_.loc[df_['fields_of_study'] == 'Matematik Mühendisligi (%100 Ingilizce)', 'fields_of_study'] = 'Mathematical Engineering'
    df_.loc[df_['fields_of_study'] == 'Department of Mathematical Engineering / Matematik Mühendisliği', 'fields_of_study'] = 'Mathematical Engineering'
    df_.loc[df_['fields_of_study'] == 'Matematik Mühendisliği (%100 İngilizce)', 'fields_of_study'] = 'Mathematical Engineering'
    df_.loc[df_['fields_of_study'] == 'Matematik Mühendisliği (Ingilizce) ', 'fields_of_study'] = 'Mathematical Engineering'
    df_.loc[df_['fields_of_study'] == 'Kimya Metalurji fakültesi, Matematik Mühendisliği', 'fields_of_study'] = 'Mathematical Engineering'
    df_.loc[df_['fields_of_study'] == 'Matematik Mühendisliği Yüksek Lisans', 'fields_of_study'] = 'Mathematical Engineering'
    df_.loc[df_['fields_of_study'] == 'Matematik mühendisliği', 'fields_of_study'] = 'Mathematical Engineering'
    df_.loc[df_['fields_of_study'] == 'Matematik mühendisliği ', 'fields_of_study'] = 'Mathematical Engineering'
    df_.loc[df_['fields_of_study'] == 'Matematik mühendisliği 3.33', 'fields_of_study'] = 'Mathematical Engineering'
    df_.loc[df_['fields_of_study'] == 'matematik mühendisliği', 'fields_of_study'] = 'Mathematical Engineering'
    df_.loc[df_['fields_of_study'] == 'matematik mühendisi', 'fields_of_study'] = 'Mathematical Engineering'
    df_.loc[df_['fields_of_study'] == 'matematik mühendisliği / mathematical engineering', 'fields_of_study'] = 'Mathematical Engineering'
    df_.loc[df_['fields_of_study'] == 'mathematical enginering', 'fields_of_study'] = 'Mathematical Engineering'
    df_.loc[df_['fields_of_study'] == 'mathematical Engineering', 'fields_of_study'] = 'Mathematical Engineering'
    df_.loc[df_['fields_of_study'] == 'mathematical engineering', 'fields_of_study'] = 'Mathematical Engineering'
    
    df_.loc[df_['fields_of_study'] == 'Kimya Mühendisliği', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'Chemical Engineering', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'Chemical Engineer', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'Chemical engineering', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'Chemical and Biological Engineering', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'Chemical engineer', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'Department of Chemical Engineering', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'Chemical and Biological Engineering (English)', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'Chemical Process Technology', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'Chemical Engineering ', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'Chemical Food Engineering', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'Chemical Engineering, Polymer', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'Chemical Engineering-Transition to Computer Engineering/Drop out', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'Chemical Engineering/Chemical Technologics', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'Chemical Engineering, 3.55/4, Graduated with third degree', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'Chemical Engineering, 3.97', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'Chemical Engineering (%100 English)', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'Chemical Engineering, 3.64', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'Chemical Technologies', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'Chemical Engineering Department', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'Chemical Engineering / Master', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'Chemical Engineering', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'Chemical Engineering Process and Reactor Design', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'Chemical Engineering and Applied Chemistry %100 Scholarship', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'Master Student (thesis stage), Chemical Engineering', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'B.S., Chemical Engineering', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'B.Sc Chemical Engineering', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'Chemical and Biochemical Engineering', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == "Chemical Engineering Master's Programme", 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'Chemical and Bioprocess Engineering', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'B.Sc.,Chemical Engineering', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'M.Sc. Chemical Engineering', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'M.Sc., Chemical Engineering', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'BSc, Chemical Engineering', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'MSc, Chemical Engineering', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'Kimya Mühendisliği - Chemical Engineering', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'Chemical, Biological, Radiological and Nuclear Defense', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'Chemical and Process Engineering', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'B.Sc. Chemical Engineering', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'Chemical Enginnering', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'chemical engineering', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'chemical engineer', 'fields_of_study'] = 'Chemical Engineering'
    df_.loc[df_['fields_of_study'] == 'chemical', 'fields_of_study'] = 'Chemical Engineering'

    df_.loc[df_['fields_of_study'] == 'Computer Engineer', 'fields_of_study'] = 'Computer Engineering'
    df_.loc[df_['fields_of_study'] == 'Electrical and Electronic Engineering', 'fields_of_study'] = 'Electrical and Electronics Engineering'
    df_.loc[df_['fields_of_study'] == 'Electrical & Electronics Engineering', 'fields_of_study'] = 'Electrical and Electronics Engineering'
    df_.loc[df_['fields_of_study'] == 'Electrical-Electronics Engineering', 'fields_of_study'] = 'Electrical and Electronics Engineering'
    df_.loc[df_['fields_of_study'] == 'Electrical Electronics Engineering', 'fields_of_study'] = 'Electrical and Electronics Engineering'
    df_.loc[df_['fields_of_study'] == 'Electrical&Electronics Engineering', 'fields_of_study'] = 'Electrical and Electronics Engineering'
    df_.loc[df_['fields_of_study'] == 'Electric and Electronic Engineering', 'fields_of_study'] = 'Electrical and Electronics Engineering'
    df_.loc[df_['fields_of_study'] == 'Electrical and Electronics Engineer', 'fields_of_study'] = 'Electrical and Electronics Engineering'
    df_.loc[df_['fields_of_study'] == 'Electrical - Electronics Engineering', 'fields_of_study'] = 'Electrical and Electronics Engineering'
    df_.loc[df_['fields_of_study'] == 'Electric and Electronics Engineering', 'fields_of_study'] = 'Electrical and Electronics Engineering'
    df_.loc[df_['fields_of_study'] == 'Electrical & Electronics Engineer', 'fields_of_study'] = 'Electrical and Electronics Engineering'
    df_.loc[df_['fields_of_study'] == 'Electrics and Electronics Engineering', 'fields_of_study'] = 'Electrical and Electronics Engineering'
    df_.loc[df_['fields_of_study'] == 'Elektronik ve Haberleşme Mühendisliği', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'Elektronik ve Haberleşme Mühendisi', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'Elektronik ve Haberleşme Mühendisliği ', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'Elektronik ve Haberleşme', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'Elektronik ve Haberleşme mühendisliği', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'Elektronik ve Haberleşme Müh.', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'Elektronik ve Haberleşme Teknolojisi', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'Elektrik, Elektronik ve Haberleşme Mühendisliği', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == ' Elektronik ve Haberleşme Mühendisliği', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'Elektronik ve Habeleşme Mühendisliği', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'Elektronik ve Haberleşme Mühendisliği (İngilizce)', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == ' Elektronik ve Haberleşme Mühendisliği, Bilgisayar Mühendisliği', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'Elektronik ve Haberlesme Muhendisligi', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'Elektronik ve Haberleşme Mühendisligi', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'Elektronik ve Haberlesme Muh.', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'Lisans (BSc), Elektronik ve Haberleşme Mühendisliği', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'Yüksek Lisans (MSc), Elektronik ve Haberleşme Mühendisliği, Elektronik Programı', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'Elektronik ve Haberleşme Mühendisliği.', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'Elektronics and Communication Engineering', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'Elektronics and Communication Enginnering', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'Elektronics and Telecommunication Engineering', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'Elektronics and Communications Engineering', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'Elektronics and Communication engineering', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'electronics and communication engineering', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'electronics and Communication Engineer', 'fields_of_study'] = 'Electronics and Communication Engineering'
    df_.loc[df_['fields_of_study'] == 'electronics and commnication engineering', 'fields_of_study'] = 'Electronics and Communication Engineering'

    df_.loc[df_['fields_of_study'] == 'Bilgisayar Mühendisliği (İngilizce)', 'fields_of_study'] = 'Computer Engineering'
    df_.loc[df_['fields_of_study'] == 'Bilgisayar programcılığı', 'fields_of_study'] = 'Computer Programming'
    df_.loc[df_['fields_of_study'] == 'Bilgisayar Teknolojisi ve Programlama', 'fields_of_study'] = 'Computer Programming'
    df_.loc[df_['fields_of_study'] == 'Bilgisayar Programlama, Özel Uygulamalar', 'fields_of_study'] = 'Computer Programming'
    df_.loc[df_['fields_of_study'] == 'Bilgisayar Teknolojileri ve Programlama', 'fields_of_study'] = 'Computer Programming'
    df_.loc[df_['fields_of_study'] == 'Bilgisayar Mühendisi', 'fields_of_study'] = 'Computer Engineering'
    df_.loc[df_['fields_of_study'] == 'Bilgisayar Mühendisliği Yüksek Lisans', 'fields_of_study'] = 'Computer Engineering'
    df_.loc[df_['fields_of_study'] == 'Bilgisayar Programcılığı / Tekniker', 'fields_of_study'] = 'Computer Programming'
    df_.loc[df_['fields_of_study'] == 'B.Sc., Faculty of Computer and Information Science, Computer Engineering', 'fields_of_study'] = 'Computer Engineering'
    df_.loc[df_['fields_of_study'] == 'bilgisayar programcısı', 'fields_of_study'] = 'Computer Programming'
    df_.loc[df_['fields_of_study'] == 'bilgisayar programcılığı', 'fields_of_study'] = 'Computer Programming'
    df_.loc[df_['fields_of_study'] == 'bilgisayar programlama,bilgisayar teknoljileri', 'fields_of_study'] = 'Computer Programming'
    df_.loc[df_['fields_of_study'] == 'bilgisayar teknolojisi ve programlama', 'fields_of_study'] = 'Computer Programming'
    df_.loc[df_['fields_of_study'] == 'bilgisayar programcılığı ', 'fields_of_study'] = 'Computer Programming'
    df_.loc[df_['fields_of_study'] == 'bilgisayar programlama', 'fields_of_study'] = 'Computer Programming'
    df_.loc[df_['fields_of_study'] == 'Bilgisayar Teknolojileri ve bilgisayar programcılığı', 'fields_of_study'] = 'Computer Programming'
    df_.loc[df_['fields_of_study'] == 'Yönetim Bilgi Sistemleri, Genel', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems, General', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information System', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems (MIS)', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems and Engineering', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems and Services', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Yönetim Bilişim Sistemleri - Management Information Systems', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems ', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems-MBA', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Sciences', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Informations System', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information System (MIS)', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Auzef • Yönetim Bilişim Sistemleri / Management Information Systems', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems(MIS)', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == ' Management Information Systems', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems - MIS', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems Engineering', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'MBA-  Management Information Systems', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems (English) ', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Yönetim Bilişim Sistemleri / Management Information Systems', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems (Ph.D.)', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'IT Institute/Management Information Sytem', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'MIS - Management Information Systems', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == "Bachelor's Degree Management Information Systems", 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Master of Management Information Systems ( M.I.S. )', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems (Master)', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems, Full Scholarship', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems Master’s Program (with thesis)', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Sys. And Eng.', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems and Engineering ', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Informations System (MIS)', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems MIS', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'M.S, Management Information Systems', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems & Engineering', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'MIS(Management Information Systems)', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == ' Management Informaton Systems', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems and Engineering (MIS)', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems Technologies ', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == "Master's degree, Management Information Systems", 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Yönetim Bilişim Sistemleri ( Management Information Systems )', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'MIS Management Information Systems - Yönetim Bilişi', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems, Honours Degree', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Yüksek Lisans (Master) / Management Information Systems', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems (Wirtschaftsinformatik)', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == "Master's Degree, Management Information Systems (MIS).", 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'MIS (Management Information Systems)', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Astronomy , Computer Programming, Management Information Systems', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems (Graduate School)', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems (Success Scholarship)', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == "Faculty of Engineering Management Information Systems Master's Degree", 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems (MIS) Master', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == "Management Information Systems / Master's Degree", 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Master of Management Information Systems', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == '(MIS) Management Information Systems', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Yönetim Bilişim Sistemleri (Management Information Systems)', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == "Bachelor's Degree, Management Information Systems ", 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Technology', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Engineer Faculty - Management Information Systems', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems in German (Wirtschaftsinformatik)', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == ' Faculty of Commercial Sciences, Department of Management Information Systems', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Bachelor’s Degree in Management Information Systems', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems, General (Yönetim Bilişim Sistemleri)', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems (M.I.S)', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems (MSc)', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems (3.41/4)', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems, Full Scholarship Student', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Informatics Systems,Undergradute Program', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Informatics Systems', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems (M.I.S.)', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Yönetim Bilişim Sistemleri (MIS - Management Information Systems)', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'MBA - Management Information Systems and Services', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Yönetim Bilişim Sistemleri, Management Information Systems', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Sytems', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems,MIS', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems (Yönetim Bilişim Sistemleri)', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'MBA / Management Information Systems', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == ' Management Information System (MIS)', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems / Master', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information System (MIS) - Yönetim Bilişim Sistemleri', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == ' Management Information Systems ( Yönetim Bilişim Sistemleri )', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems Specialist ', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == "bachelor's degree • Management Information Systems", 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems, General (in German)', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == ' Management Information Systems and Engineering ', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems (German)', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information System and Engineering', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Information Systems, 3.26', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management information systems', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management information systems ', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management information system/MBA', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Yönetim bilişim sistemleri mühendisliği /Management information systems engineering (%100 İngilizce)', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management information System', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Infırmation Systems', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'Management Infomations Systems', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'yönetim bilişim ve sistemleri', 'fields_of_study'] = 'Management Information Systems'
    df_.loc[df_['fields_of_study'] == 'işletme', 'fields_of_study'] = 'İşletme'
    df_.loc[df_['fields_of_study'] == 'işletme ', 'fields_of_study'] = 'İşletme'
    df_.loc[df_['fields_of_study'] == 'işletme bölümü', 'fields_of_study'] = 'İşletme'
    df_.loc[df_['fields_of_study'] == 'işletme/işletmecilik', 'fields_of_study'] = 'İşletme'
    df_.loc[df_['fields_of_study'] == 'işletmecilik', 'fields_of_study'] = 'İşletme'
    df_.loc[df_['fields_of_study'] == 'İngilizce işletme', 'fields_of_study'] = 'İşletme'

    return df_